-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "dragon"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@comment.error", { bg = "#e82424", bold = true, fg = "#c5c9c5" })
hi(0, "@comment.note", { bg = "#6a9589", bold = true, fg = "#223249" })
hi(0, "@comment.warning", { bg = "#ff9e3b", bold = true, fg = "#223249" })
hi(0, "@constructor", { fg = "#949fb5" })
hi(0, "@constructor.lua", { fg = "#8992a7" })
hi(0, "@diff.delta", { fg = "#dca561" })
hi(0, "@diff.minus", { fg = "#c34043" })
hi(0, "@diff.plus", { fg = "#76946a" })
hi(0, "@keyword.exception", { bold = true, fg = "#c4746e" })
hi(0, "@keyword.import", { link = "PreProc" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#c4746e" })
hi(0, "@keyword.return", { fg = "#c4746e", italic = true })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.bitwise", { link = "Operator" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.comment", { link = "Comment" })
hi(0, "@lsp.type.comparison", { link = "Operator" })
hi(0, "@lsp.type.const", { link = "Constant" })
hi(0, "@lsp.type.decorator.rust", { link = "PreProc" })
hi(0, "@lsp.type.lifetime", { link = "Operator" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.punctuation", { link = "Delimiter" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#8ba4b0" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@keyword.exception" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@markup.environment", { link = "Keyword" })
hi(0, "@markup.heading", { link = "Function" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#181616", fg = "#181616", nocombine = true, sp = "#c5c9c5", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#181616", fg = "#181616", nocombine = true, sp = "#c5c9c5", underline = true })
hi(0, "@markup.link.url", { link = "@string.special.url" })
hi(0, "@markup.math", { link = "Constant" })
hi(0, "@markup.quote", { link = "@variable.parameter" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@punctuation.bracket", { fg = "#9e9b93" })
hi(0, "@punctuation.delimiter", { fg = "#9e9b93" })
hi(0, "@punctuation.special", { fg = "#949fb5" })
hi(0, "@string.escape", { bold = true, fg = "#c4746e" })
hi(0, "@string.regexp", { fg = "#c4746e" })
hi(0, "@string.special.symbol", { fg = "#c4b28a" })
hi(0, "@string.special.url", { fg = "#949fb5", undercurl = true })
hi(0, "@tag.attribute", { fg = "#c4b28a" })
hi(0, "@tag.delimiter", { fg = "#9e9b93" })
hi(0, "@variable", { fg = "#c5c9c5" })
hi(0, "@variable.builtin", { fg = "#c4746e", italic = true })
hi(0, "@variable.member", { fg = "#c4b28a" })
hi(0, "@variable.parameter", { fg = "#a6a69c" })
hi(0, "AerialArrayIcon", { link = "Type" })
hi(0, "AerialBooleanIcon", { link = "Boolean" })
hi(0, "AerialClassIcon", { link = "Type" })
hi(0, "AerialConstantIcon", { link = "Constant" })
hi(0, "AerialConstructorIcon", { link = "@constructor" })
hi(0, "AerialEnumIcon", { link = "Type" })
hi(0, "AerialEnumMemberIcon", { link = "Constant" })
hi(0, "AerialEventIcon", { link = "Structure" })
hi(0, "AerialFieldIcon", { link = "@variable.member" })
hi(0, "AerialFileIcon", { link = "Directory" })
hi(0, "AerialFunctionIcon", { link = "Function" })
hi(0, "AerialInterfaceIcon", { link = "Type" })
hi(0, "AerialKeyIcon", { link = "Identifier" })
hi(0, "AerialMethodIcon", { link = "@function.method" })
hi(0, "AerialModuleIcon", { link = "@module" })
hi(0, "AerialNamespaceIcon", { link = "@module" })
hi(0, "AerialNullIcon", { link = "Type" })
hi(0, "AerialNumberIcon", { link = "Number" })
hi(0, "AerialObjectIcon", { link = "Type" })
hi(0, "AerialOperatorIcon", { link = "Operator" })
hi(0, "AerialPackageIcon", { link = "@module" })
hi(0, "AerialPropertyIcon", { link = "@property" })
hi(0, "AerialStringIcon", { link = "String" })
hi(0, "AerialStructIcon", { link = "Structure" })
hi(0, "AerialTypeParameterIcon", { link = "Type" })
hi(0, "AerialVariableIcon", { link = "@variable" })
hi(0, "BlinkCmpDoc", { link = "NormalFloat" })
hi(0, "BlinkCmpDocBorder", { link = "FloatBorder" })
hi(0, "BlinkCmpDocCursorLine", { link = "Visual" })
hi(0, "BlinkCmpGhostText", { fg = "#737c73" })
hi(0, "BlinkCmpKind", { fg = "#c8c093" })
hi(0, "BlinkCmpKindClass", { link = "Type" })
hi(0, "BlinkCmpKindColor", { link = "Special" })
hi(0, "BlinkCmpKindConstant", { link = "Constant" })
hi(0, "BlinkCmpKindConstructor", { link = "@constructor" })
hi(0, "BlinkCmpKindCopilot", { link = "String" })
hi(0, "BlinkCmpKindEnum", { link = "Type" })
hi(0, "BlinkCmpKindEnumMember", { link = "Constant" })
hi(0, "BlinkCmpKindEvent", { link = "Type" })
hi(0, "BlinkCmpKindField", { link = "@variable.member" })
hi(0, "BlinkCmpKindFile", { link = "Directory" })
hi(0, "BlinkCmpKindFolder", { link = "Directory" })
hi(0, "BlinkCmpKindFunction", { link = "Function" })
hi(0, "BlinkCmpKindInterface", { link = "Type" })
hi(0, "BlinkCmpKindKeyword", { link = "Keyword" })
hi(0, "BlinkCmpKindMethod", { link = "@function.method" })
hi(0, "BlinkCmpKindModule", { link = "@module" })
hi(0, "BlinkCmpKindOperator", { link = "Operator" })
hi(0, "BlinkCmpKindProperty", { link = "@property" })
hi(0, "BlinkCmpKindReference", { link = "Special" })
hi(0, "BlinkCmpKindSnippet", { link = "Special" })
hi(0, "BlinkCmpKindStruct", { link = "Type" })
hi(0, "BlinkCmpKindText", { fg = "#c5c9c5" })
hi(0, "BlinkCmpKindTypeParameter", { link = "Type" })
hi(0, "BlinkCmpKindUnit", { link = "Number" })
hi(0, "BlinkCmpKindValue", { link = "String" })
hi(0, "BlinkCmpKindVariable", { fg = "#c8c093" })
hi(0, "BlinkCmpLabel", { fg = "#dcd7ba" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#737c73", strikethrough = true })
hi(0, "BlinkCmpLabelDetails", { fg = "#737c73" })
hi(0, "BlinkCmpLabelMatch", { fg = "#8ba4b0" })
hi(0, "BlinkCmpMenu", { link = "Pmenu" })
hi(0, "BlinkCmpMenuBorder", { bg = "#223249", fg = "#2d4f67" })
hi(0, "BlinkCmpMenuSelection", { link = "PmenuSel" })
hi(0, "BlinkCmpScrollBarGutter", { link = "PmenuSbar" })
hi(0, "BlinkCmpScrollBarThumb", { link = "PmenuThumb" })
hi(0, "BlinkCmpSignatureHelp", { link = "NormalFloat" })
hi(0, "BlinkCmpSignatureHelpActiveParameter", { link = "LspSignatureActiveParameter" })
hi(0, "BlinkCmpSignatureHelpBorder", { link = "FloatBorder" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#b6927b" })
hi(0, "Character", { link = "String" })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#223249", fg = "#2d4f67" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { link = "PmenuSel" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpGhostText", { fg = "#737c73" })
hi(0, "CmpItemAbbr", { fg = "#dcd7ba" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#737c73", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#8ba4b0" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindCopilot", { link = "String" })
hi(0, "CmpItemKindDefault", { fg = "#c8c093" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEvent", { link = "Type" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "@function.method" })
hi(0, "CmpItemKindModule", { link = "@module" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindReference", { link = "Special" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindText", { fg = "#c5c9c5" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Number" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindVariable", { fg = "#c8c093" })
hi(0, "CmpItemMenu", { fg = "#c8c093" })
hi(0, "ColorColumn", { bg = "#282727" })
hi(0, "Comment", { fg = "#737c73", italic = true })
hi(0, "Conceal", { bold = true, fg = "#7a8382" })
hi(0, "Constant", { fg = "#b6927b" })
hi(0, "CurSearch", { bg = "#2d4f67", bold = true, fg = "#c5c9c5" })
hi(0, "Cursor", { bg = "#c5c9c5", fg = "#181616" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#393836" })
hi(0, "CursorLineNr", { bg = "#282727", bold = true, fg = "#ff9e3b" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c4b28a" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#658594" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#54546d" })
hi(0, "DapUIFloatBorder", { fg = "#54546d" })
hi(0, "DapUILineNumber", { fg = "#949fb5" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#949fb5" })
hi(0, "DapUIPlayPause", { fg = "#8a9a7b" })
hi(0, "DapUIRestart", { fg = "#8a9a7b" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#c4746e" })
hi(0, "DapUIStepBack", { fg = "#949fb5" })
hi(0, "DapUIStepInto", { fg = "#949fb5" })
hi(0, "DapUIStepOut", { fg = "#949fb5" })
hi(0, "DapUIStepOver", { fg = "#949fb5" })
hi(0, "DapUIStop", { fg = "#e82424" })
hi(0, "DapUIStoppedThread", { fg = "#949fb5" })
hi(0, "DapUIThread", { fg = "#c4b28a" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#737c73" })
hi(0, "DapUIWatchesEmpty", { fg = "#e82424" })
hi(0, "DapUIWatchesError", { fg = "#e82424" })
hi(0, "DapUIWatchesValue", { fg = "#c4b28a" })
hi(0, "DashboardCenter", { fg = "#c4b28a" })
hi(0, "DashboardDesc", { fg = "#c4b28a" })
hi(0, "DashboardFooter", { fg = "#737c73" })
hi(0, "DashboardHeader", { fg = "#c34043" })
hi(0, "DashboardIcon", { fg = "#7a8382" })
hi(0, "DashboardKey", { fg = "#949fb5" })
hi(0, "DashboardShortCut", { fg = "#949fb5" })
hi(0, "Delimiter", { fg = "#9e9b93" })
hi(0, "DiagnosticError", { fg = "#e82424" })
hi(0, "DiagnosticFloatingError", { fg = "#e82424" })
hi(0, "DiagnosticFloatingHint", { fg = "#6a9589" })
hi(0, "DiagnosticFloatingInfo", { fg = "#658594" })
hi(0, "DiagnosticFloatingOk", { fg = "#98bb6c" })
hi(0, "DiagnosticFloatingWarn", { fg = "#ff9e3b" })
hi(0, "DiagnosticHint", { fg = "#6a9589" })
hi(0, "DiagnosticInfo", { fg = "#658594" })
hi(0, "DiagnosticOk", { fg = "#98bb6c" })
hi(0, "DiagnosticSignError", { bg = "#282727", fg = "#e82424" })
hi(0, "DiagnosticSignHint", { bg = "#282727", fg = "#6a9589" })
hi(0, "DiagnosticSignInfo", { bg = "#282727", fg = "#658594" })
hi(0, "DiagnosticSignWarn", { bg = "#282727", fg = "#ff9e3b" })
hi(0, "DiagnosticUnderlineError", { sp = "#e82424", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6a9589", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#658594", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ff9e3b", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#ff9e3b" })
hi(0, "DiffAdd", { bg = "#2b3328" })
hi(0, "DiffChange", { bg = "#252535" })
hi(0, "DiffDelete", { bg = "#43242b", fg = "#c34043" })
hi(0, "DiffText", { bg = "#49443c" })
hi(0, "Directory", { fg = "#8ba4b0" })
hi(0, "EndOfBuffer", { fg = "#181616" })
hi(0, "Error", { fg = "#e82424" })
hi(0, "ErrorMsg", { fg = "#e82424" })
hi(0, "Exception", { fg = "#c4746e" })
hi(0, "FloatBorder", { bg = "#0d0c0c", fg = "#54546d" })
hi(0, "FloatFooter", { bg = "#0d0c0c", fg = "#625e5a" })
hi(0, "FloatTitle", { bg = "#0d0c0c", bold = true, fg = "#7a8382" })
hi(0, "FloatermBorder", { bg = "#181616", fg = "#54546d" })
hi(0, "FoldColumn", { bg = "#282727", fg = "#625e5a" })
hi(0, "Folded", { bg = "#282727", fg = "#7a8382" })
hi(0, "Function", { fg = "#8ba4b0" })
hi(0, "GitSignsAdd", { bg = "#282727", fg = "#76946a" })
hi(0, "GitSignsChange", { bg = "#282727", fg = "#dca561" })
hi(0, "GitSignsDelete", { bg = "#282727", fg = "#c34043" })
hi(0, "IblIndent", { fg = "#625e5a" })
hi(0, "IblScope", { fg = "#7a8382" })
hi(0, "IblWhitespace", { fg = "#625e5a" })
hi(0, "Identifier", { fg = "#c4b28a" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IncSearch", { bg = "#ff9e3b", fg = "#223249" })
hi(0, "IndentBlanklineChar", { fg = "#625e5a" })
hi(0, "IndentBlanklineContextChar", { fg = "#7a8382" })
hi(0, "IndentBlanklineContextStart", { sp = "#7a8382", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#625e5a" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#625e5a" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#8992a7", italic = true })
hi(0, "LazyProgressTodo", { fg = "#625e5a" })
hi(0, "LineNr", { bg = "#282727", fg = "#625e5a" })
hi(0, "LspCodeLens", { fg = "#737c73" })
hi(0, "LspReferenceText", { bg = "#49443c" })
hi(0, "LspReferenceWrite", { bg = "#49443c", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#ff9e3b" })
hi(0, "MatchParen", { bold = true, fg = "#ff9e3b" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { fg = "#6a9589" })
hi(0, "MiniDepsInfo", { fg = "#658594" })
hi(0, "MiniDepsMsgBreaking", { fg = "#ff9e3b" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { bg = "#282727", fg = "#76946a" })
hi(0, "MiniDiffSignChange", { bg = "#282727", fg = "#dca561" })
hi(0, "MiniDiffSignDelete", { bg = "#282727", fg = "#c34043" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#c5c9c5" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#0d0c0c", bold = true, fg = "#7a8382" })
hi(0, "MiniFilesTitleFocused", { bg = "#0d0c0c", bold = true, fg = "#c5c9c5" })
hi(0, "MiniHipatternsFixme", { bg = "#e82424", bold = true, fg = "#181616" })
hi(0, "MiniHipatternsHack", { bg = "#ff9e3b", bold = true, fg = "#181616" })
hi(0, "MiniHipatternsNote", { bg = "#658594", bold = true, fg = "#181616" })
hi(0, "MiniHipatternsTodo", { bg = "#6a9589", bold = true, fg = "#181616" })
hi(0, "MiniIconsAzure", { fg = "#949fb5" })
hi(0, "MiniIconsBlue", { fg = "#8ba4b0" })
hi(0, "MiniIconsCyan", { fg = "#8ea4a2" })
hi(0, "MiniIconsGreen", { fg = "#8a9a7b" })
hi(0, "MiniIconsGrey", { fg = "#c5c9c5" })
hi(0, "MiniIconsOrange", { fg = "#b6927b" })
hi(0, "MiniIconsPurple", { fg = "#8992a7" })
hi(0, "MiniIconsRed", { fg = "#c4746e" })
hi(0, "MiniIconsYellow", { fg = "#c4b28a" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#949fb5" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#b6927b", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#12120f", fg = "#6a9589", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#949fb5", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#0d0c0c", fg = "#8ba4b0" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#717c7c" })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Delimiter" })
hi(0, "MiniStarterItemPrefix", { fg = "#ff9e3b" })
hi(0, "MiniStarterQuery", { fg = "#658594" })
hi(0, "MiniStarterSection", { fg = "#98bb6c" })
hi(0, "MiniStatuslineDevinfo", { bg = "#282727", fg = "#c8c093" })
hi(0, "MiniStatuslineFileinfo", { bg = "#282727", fg = "#c8c093" })
hi(0, "MiniStatuslineFilename", { bg = "#12120f", fg = "#c8c093" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#c4746e", bold = true, fg = "#181616" })
hi(0, "MiniStatuslineModeInsert", { bg = "#98bb6c", bold = true, fg = "#181616" })
hi(0, "MiniStatuslineModeNormal", { bg = "#8ba4b0", bold = true, fg = "#0d0c0c" })
hi(0, "MiniStatuslineModeOther", { bg = "#8ea4a2", bold = true, fg = "#181616" })
hi(0, "MiniStatuslineModeReplace", { bg = "#b6927b", bold = true, fg = "#181616" })
hi(0, "MiniStatuslineModeVisual", { bg = "#8992a7", bold = true, fg = "#181616" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#282727", bold = true, fg = "#c8c093" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#0d0c0c", fg = "#7a8382" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#c8c093", bold = true, fg = "#282727" })
hi(0, "MiniTablineModifiedHidden", { bg = "#7a8382", fg = "#0d0c0c" })
hi(0, "MiniTablineModifiedVisible", { bg = "#7a8382", bold = true, fg = "#0d0c0c" })
hi(0, "MiniTablineTabpagesection", { bg = "#2d4f67", bold = true, fg = "#c5c9c5" })
hi(0, "MiniTablineVisible", { bg = "#0d0c0c", bold = true, fg = "#7a8382" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#e82424" })
hi(0, "MiniTestPass", { bold = true, fg = "#98bb6c" })
hi(0, "MiniTrailspace", { bg = "#c34043" })
hi(0, "ModeMsg", { bold = true, fg = "#ff9e3b" })
hi(0, "MoreMsg", { fg = "#658594" })
hi(0, "MsgArea", { fg = "#c8c093" })
hi(0, "MsgSeparator", { bg = "#0d0c0c" })
hi(0, "NavicIconsArray", { link = "Type" })
hi(0, "NavicIconsBoolean", { link = "Boolean" })
hi(0, "NavicIconsClass", { link = "Type" })
hi(0, "NavicIconsConstant", { link = "Constant" })
hi(0, "NavicIconsConstructor", { link = "@constructor" })
hi(0, "NavicIconsEnum", { link = "Type" })
hi(0, "NavicIconsEnumMember", { link = "Constant" })
hi(0, "NavicIconsEvent", { link = "Structure" })
hi(0, "NavicIconsField", { link = "@variable.member" })
hi(0, "NavicIconsFile", { link = "Directory" })
hi(0, "NavicIconsFunction", { link = "Function" })
hi(0, "NavicIconsInterface", { link = "Type" })
hi(0, "NavicIconsKey", { link = "Identifier" })
hi(0, "NavicIconsMethod", { link = "@function.method" })
hi(0, "NavicIconsModule", { link = "@module" })
hi(0, "NavicIconsNamespace", { link = "@module" })
hi(0, "NavicIconsNull", { link = "Type" })
hi(0, "NavicIconsNumber", { link = "Number" })
hi(0, "NavicIconsObject", { link = "Type" })
hi(0, "NavicIconsOperator", { link = "Operator" })
hi(0, "NavicIconsPackage", { link = "@module" })
hi(0, "NavicIconsProperty", { link = "@property" })
hi(0, "NavicIconsString", { link = "String" })
hi(0, "NavicIconsStruct", { link = "Structure" })
hi(0, "NavicIconsTypeParameter", { link = "Type" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { fg = "#c5c9c5" })
hi(0, "NavicText", { fg = "#c5c9c5" })
hi(0, "NeoTreeGitAdded", { fg = "#76946a" })
hi(0, "NeoTreeGitConflict", { fg = "#e82424" })
hi(0, "NeoTreeGitDeleted", { fg = "#c34043" })
hi(0, "NeoTreeGitModified", { fg = "#dca561" })
hi(0, "NeoTreeGitStaged", { fg = "#76946a" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#c4b28a" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitDiffAddHighlight", { bg = "#2b3328" })
hi(0, "NeogitDiffContextHighlight", { bg = "#252535" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#43242b" })
hi(0, "NeogitHunkHeader", { fg = "#8ba4b0" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#252535", fg = "#b6927b" })
hi(0, "NeotestAdapterName", { fg = "#c4746e" })
hi(0, "NeotestDir", { fg = "#8ba4b0" })
hi(0, "NeotestExpandMarker", { bold = true, fg = "#9e9b93" })
hi(0, "NeotestFailed", { fg = "#e82424" })
hi(0, "NeotestFile", { fg = "#8ba4b0" })
hi(0, "NeotestFocused", { bold = true, underline = true })
hi(0, "NeotestIndent", { bold = true, fg = "#7a8382" })
hi(0, "NeotestMarked", { fg = "#ff9e3b", italic = true })
hi(0, "NeotestNamespace", { fg = "#8ba4b0" })
hi(0, "NeotestPassed", { fg = "#98bb6c" })
hi(0, "NeotestRunning", { fg = "#dca561" })
hi(0, "NeotestSkipped", { fg = "#949fb5" })
hi(0, "NeotestTarget", { fg = "#c4746e" })
hi(0, "NeotestTest", { fg = "#c8c093" })
hi(0, "NeotestUnknown", { fg = "#717c7c" })
hi(0, "NeotestWatching", { fg = "#dca561" })
hi(0, "NeotestWinSelect", { fg = "#6a9589" })
hi(0, "NonText", { fg = "#625e5a" })
hi(0, "Normal", { bg = "#0a0a0a", fg = "#c5c9c5" })
hi(0, "NormalFloat", { bg = "#0d0c0c", fg = "#c8c093" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyBackground", { bg = "#181616" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "Number", { fg = "#a292a3" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#8a9a7b" })
hi(0, "NvimTreeFolderName", { link = "Directory" })
hi(0, "NvimTreeGitDeleted", { fg = "#c34043" })
hi(0, "NvimTreeGitDirty", { fg = "#dca561" })
hi(0, "NvimTreeGitNew", { fg = "#76946a" })
hi(0, "NvimTreeGitStaged", { fg = "#76946a" })
hi(0, "NvimTreeImageFile", { fg = "#c4746e" })
hi(0, "NvimTreeNormal", { link = "Normal" })
hi(0, "NvimTreeNormalNC", { link = "NvimTreeNormal" })
hi(0, "NvimTreeOpenedFile", { fg = "#949fb5", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c4b28a" })
hi(0, "NvimTreeSpecialFile", { fg = "#949fb5" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWinSeparator", { link = "WinSeparator" })
hi(0, "NvimTreeWindowPicker", { bg = "#1d1c19", bold = true, fg = "#949fb5" })
hi(0, "Operator", { fg = "#c4746e" })
hi(0, "Pmenu", { bg = "#223249", fg = "#dcd7ba" })
hi(0, "PmenuExtra", { bg = "#223249", fg = "#7a8382" })
hi(0, "PmenuExtraSel", { bg = "#2d4f67", fg = "#7a8382" })
hi(0, "PmenuKind", { bg = "#223249", fg = "#c8c093" })
hi(0, "PmenuKindSel", { bg = "#2d4f67", fg = "#c8c093" })
hi(0, "PmenuSbar", { bg = "#223249" })
hi(0, "PmenuSel", { bg = "#2d4f67" })
hi(0, "PmenuThumb", { bg = "#2d4f67" })
hi(0, "PreProc", { fg = "#c4746e" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#282727" })
hi(0, "Search", { bg = "#2d4f67", fg = "#c5c9c5" })
hi(0, "SignColumn", { bg = "#282727", fg = "#7a8382" })
hi(0, "Special", { fg = "#949fb5" })
hi(0, "SpecialKey", { fg = "#7a8382" })
hi(0, "SpellBad", { sp = "#e82424", undercurl = true })
hi(0, "SpellCap", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellLocal", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellRare", { sp = "#ff9e3b", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#8992a7" })
hi(0, "StatusLine", { bg = "#0d0c0c", fg = "#c8c093" })
hi(0, "StatusLineNC", { bg = "#0d0c0c", fg = "#625e5a" })
hi(0, "String", { fg = "#8a9a7b" })
hi(0, "Substitute", { bg = "#c34043", fg = "#c5c9c5" })
hi(0, "TabLine", { bg = "#0d0c0c", fg = "#7a8382" })
hi(0, "TabLineFill", { bg = "#181616" })
hi(0, "TabLineSel", { bg = "#282727", fg = "#c8c093" })
hi(0, "TelescopeBorder", { bg = "#181616", fg = "#54546d" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { fg = "#7a8382" })
hi(0, "Title", { bold = true, fg = "#8ba4b0" })
hi(0, "Todo", { bg = "#658594", bold = true, fg = "#223249" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextLineNumber", { bg = "#282727", fg = "#7a8382" })
hi(0, "TroubleIndent", { fg = "#625e5a" })
hi(0, "TroublePos", { fg = "#7a8382" })
hi(0, "Type", { fg = "#8ea4a2" })
hi(0, "Underlined", { fg = "#949fb5", underline = true })
hi(0, "Visual", { bg = "#223249" })
hi(0, "WarningMsg", { fg = "#ff9e3b" })
hi(0, "Whitespace", { fg = "#625e5a" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#c8c093" })
hi(0, "WinBarNC", { fg = "#c8c093" })
hi(0, "WinSeparator", { fg = "#0d0c0c" })
hi(0, "debugBreakpoint", { bg = "#282727", fg = "#949fb5" })
hi(0, "debugPC", { bg = "#43242b" })
hi(0, "diffAdded", { fg = "#76946a" })
hi(0, "diffChanged", { fg = "#dca561" })
hi(0, "diffDeleted", { fg = "#c34043" })
hi(0, "diffNewFile", { fg = "#76946a" })
hi(0, "diffOldFile", { fg = "#c34043" })
hi(0, "diffRemoved", { fg = "#c34043" })
hi(0, "healthError", { fg = "#e82424" })
hi(0, "healthSuccess", { fg = "#98bb6c" })
hi(0, "healthWarning", { fg = "#ff9e3b" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "markdownCode", { fg = "#8a9a7b" })
hi(0, "markdownCodeBlock", { fg = "#8a9a7b" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#0d0c0c"
g.terminal_color_1 = "#c4746e"
g.terminal_color_2 = "#8a9a7b"
g.terminal_color_3 = "#c4b28a"
g.terminal_color_4 = "#8ba4b0"
g.terminal_color_5 = "#a292a3"
g.terminal_color_6 = "#8ea4a2"
g.terminal_color_7 = "#c8c093"
g.terminal_color_8 = "#a6a69c"
g.terminal_color_9 = "#e46876"
g.terminal_color_10 = "#87a987"
g.terminal_color_11 = "#e6c384"
g.terminal_color_12 = "#7fb4ca"
g.terminal_color_13 = "#938aa9"
g.terminal_color_14 = "#7aa89f"
g.terminal_color_15 = "#c5c9c5"
